### ISSUE TITLE
荣耀6p运行蹦了

### ISSUE THREAD

**Issue by abero1993** [Piasy/VideoCRE#6]
FATAL EXCEPTION: HwAvcEncoderThread
                                                                                  Process: com.github.piasy.videocre.example, PID: 9822
                                                                                  java.lang.RuntimeException: Can not find HW encoder for VIDEO_CODEC_H264
                                                                                      at org.webrtc.MediaCodecVideoEncoder.initEncode(MediaCodecVideoEncoder.java:475)
                                                                                      at com.github.piasy.videocre.HwAvcEncoder$1.run(HwAvcEncoder.java:39)
                                                                                      at android.os.Handler.handleCallback(Handler.java:743)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:150)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61

**Comment by abero1993** [comment]
我知道了要配置MediaCodecProperties[] h264HwList

**Comment by chengc630** [comment]
@abero1993 请教一下是怎么配置的，我用华为p10也有这个问题
